# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField(default=0)),
                ('ShoppingDate', models.DateTimeField()),
                ('RecordDate', models.DateTimeField(verbose_name='date published')),
                ('Goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CountMyMoney.Goods')),
            ],
        ),
    ]
